aaaa/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'bookers#top'
  resources :bookers
end

aaaa/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

aaaa/app/models/book.rb
class Book < ApplicationRecord
end

aaaa/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

aaaa/app/controllers/bookers_controller.rb
class BookersController < ApplicationController
  def top
  end

  def index
  end

  def show
    @Book = Book.find(params[:id])
  end

private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

aaaa/app/helpers/application_helper.rb
module ApplicationHelper
end

aaaa/app/helpers/bookers_helper.rb
module BookersHelper
end

aaaa/app/views/book/index.html.erb
<!DOCTYPE html>

<html><head><style type="text/css">.turbolinks-progress-bar {
  position: fixed;
  display: block;
  top: 0;
  left: 0;
  height: 3px;
  background: #0076ff;
  z-index: 9999;
  transition: width 300ms ease-out, opacity 150ms 150ms ease-in;
  transform: translate3d(0, 0, 0);
}</style>




    <link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload">
    <script src="/assets/application-4e370d3723b6f204426a9414077d365ea07814cce5619ae24fb7e581988f19ed.js" data-turbolinks-track="reload"></script>
  <title>WebCampBackendNew</title><meta name="csrf-param" content="authenticity_token"><meta name="csrf-token" content="EGt/c+uo/nqd7AecAccjVQLfZU+w8l00kDwMiLGB4UZIPVhe5kaPtJ+mvat/clN3sUmFRAHbDDoFebPCLUfT7A=="></head>

  <body>
    <p id="notice"></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>リーダブルコード</td>
        <td>より良いコードを書くためのシンプルで実践的なテクニック</td>
        <td><a class="show_233524" href="/books/233524">Show</a></td>
        <td><a class="edit_233524" href="/books/233524/edit">Edit</a></td>
        <td><a data-confirm="Are you sure?" class="destroy_233524" rel="nofollow" data-method="delete" href="/books/233524">Destroy</a></td>
      </tr>
      <tr>
        <td>トラブル知らずのシステム設計</td>
        <td>システム設計の要点を図解で説明してくれます</td>
        <td><a class="show_233525" href="/books/233525">Show</a></td>
        <td><a class="edit_233525" href="/books/233525/edit">Edit</a></td>
        <td><a data-confirm="Are you sure?" class="destroy_233525" rel="nofollow" data-method="delete" href="/books/233525">Destroy</a></td>
      </tr>
      <tr>
        <td>たのしいRuby</td>
        <td>Rubyの入門におすすめです</td>
        <td><a class="show_233526" href="/books/233526">Show</a></td>
        <td><a class="edit_233526" href="/books/233526/edit">Edit</a></td>
        <td><a data-confirm="Are you sure?" class="destroy_233526" rel="nofollow" data-method="delete" href="/books/233526">Destroy</a></td>
      </tr>
      <tr>
        <td>入門Git</td>
        <td>gitについての基本操作から内部構造まで解説してくれます</td>
        <td><a class="show_233527" href="/books/233527">Show</a></td>
        <td><a class="edit_233527" href="/books/233527/edit">Edit</a></td>
        <td><a data-confirm="Are you sure?" class="destroy_233527" rel="nofollow" data-method="delete" href="/books/233527">Destroy</a></td>
      </tr>
      <tr>
        <td>アルゴリズム図鑑</td>
        <td>アルゴリズムについてカラーイラストでしっかり解説してくれます</td>
        <td><a class="show_233528" href="/books/233528">Show</a></td>
        <td><a class="edit_233528" href="/books/233528/edit">Edit</a></td>
        <td><a data-confirm="Are you sure?" class="destroy_233528" rel="nofollow" data-method="delete" href="/books/233528">Destroy</a></td>
      </tr>
      <tr>
        <td>達人プログラマー</td>
        <td>プログラマ入門者は必読！</td>
        <td><a class="show_233529" href="/books/233529">Show</a></td>
        <td><a class="edit_233529" href="/books/233529/edit">Edit</a></td>
        <td><a data-confirm="Are you sure?" class="destroy_233529" rel="nofollow" data-method="delete" href="/books/233529">Destroy</a></td>
      </tr>
      <tr>
        <td>データベース実践入門</td>
        <td>効率的なSQL文を教えてくれます</td>
        <td><a class="show_233530" href="/books/233530">Show</a></td>
        <td><a class="edit_233530" href="/books/233530/edit">Edit</a></td>
        <td><a data-confirm="Are you sure?" class="destroy_233530" rel="nofollow" data-method="delete" href="/books/233530">Destroy</a></td>
      </tr>
      <tr>
        <td>a-</td>
        <td>a-</td>
        <td><a class="show_233531" href="/books/233531">Show</a></td>
        <td><a class="edit_233531" href="/books/233531/edit">Edit</a></td>
        <td><a data-confirm="Are you sure?" class="destroy_233531" rel="nofollow" data-method="delete" href="/books/233531">Destroy</a></td>
      </tr>
  </tbody>
</table>


<h2>New book</h2>
<form class="new_book" id="new_book" action="/books" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="EGt/c+uo/nqd7AecAccjVQLfZU+w8l00kDwMiLGB4UZIPVhe5kaPtJ+mvat/clN3sUmFRAHbDDoFebPCLUfT7A==">

  <div class="field">
    <label for="book_title">Title</label>
    <input class="book_title" type="text" name="book[title]" id="book_title">
  </div>

  <div class="field">
    <label for="book_body">Body</label>
    <textarea class="book_body" name="book[body]" id="book_body" style="margin: 0px; width: 160px; height: 71px;"></textarea>
  </div>

  <div class="actions">
    <input type="submit" name="commit" value="Create Book" data-disable-with="Create Book">
  </div>
</form>


</body></html>

aaaa/app/views/book/show.html.erb
<p>
  <strong>Title:</strong>
  リーダブルコード
</p>
<p>
  <strong>Body:</strong>
  より良いコードを書くためのシンプルで実践的なテクニック
</p>
<a class="back" href="/books">Back</a>
<a class="edit_233548" href="/books/233548/edit">Edit</a>

aaaa/app/views/book/top.html.erb
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<span>
    <%= link_to "start", bookers_path %>
  </span>

aaaa/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>